version: '3.8'

services:
  mes:
    build: .
    ports:
      - "8001:8001"
    environment:
      - API_KEY=${MES_API_KEY:-mes-dev-key-123}
      - OLLAMA_HOST=http://ollama:11434
      - MAX_LOADED_MODELS=2
      - DEFAULT_TIMEOUT=30
      - LOG_LEVEL=INFO
      - PORT=8001
    volumes:
      - ./config:/app/config
    depends_on:
      - ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_models:
    driver: local
